name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"

# اگر می‌خواهی از Cloudflare Pages استفاده کنی، این بخش را uncomment کن
# [site]
# bucket = "./public"
